### ISSUE TITLE
transitive_closure broken for pip package, version = 2019.1.2

### ISSUE THREAD

**Issue by thisiscam** [inducer/islpy#23]
This is for a freshly installed islpy from pip on Python 3.6.8:
```
>>> import islpy
>>> islpy.UnionMap.transitive_closure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'UnionMap' has no attribute 'transitive_closure'
```

**Comment by thisiscam** [comment]
I just tested that version=2018.2 still works

**Comment by inducer** [comment]
Not islpy's fault IMO. Recent isl seems to have moved this to `UnionSet`: https://documen.tician.de/islpy/ref_fundamental.html#islpy.UnionMap.transitive_closure

**Comment by inducer** [comment]
Yikes, I mean `UnionMap` of course.

**Comment by thisiscam** [comment]
I see that http://isl.gforge.inria.fr/user.html has `isl_union_map_transitive_closure`, is it outdated?
I am a bit confused now... Neither `UnionSet` nor `UnionMap` is in version=2019.1.2 
```
>>> import islpy
>>> islpy.UnionSet.transitive_closure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'UnionSet' has no attribute 'transitive_closure'
>>> islpy.UnionMap.transitive_closure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'UnionMap' has no attribute 'transitive_closure'
```

**Comment by inducer** [comment]
```
>>> import islpy
>>> import islpy as isl
>>> isl.UnionMap
<class 'islpy._isl.UnionMap'>
>>> isl.UnionMap.transitive_closure
<function _add_methods.<locals>.transitive_closure at 0x7fc36145d320>
```
with bbb49d0.
