### ISSUE TITLE
no module named 'islpy._isl_cffi'

### ISSUE THREAD

**Issue by bollu** [inducer/islpy#9]
Hello,

I've tried compiling `islpy` from the `.tar.gz` providded on pypi.  I'm using `islpy-2016.2.2`.

`setup.py` succeeds, but actually trying to import `islpy` fails.

```
╰─$ python
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>   File "/Users/bollu/build/islpy-2016.2.2/islpy/_isl.py", line 14, in <module>
>>> import islpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bollu/build/islpy-2016.2.2/islpy/__init__.py", line 25, in <module>
    import islpy._isl as _isl
  File "/Users/bollu/build/islpy-2016.2.2/islpy/_isl.py", line 14, in <module>
    from islpy._isl_cffi import ffi
ModuleNotFoundError: No module named 'islpy._isl_cffi'
>>>
```

```
╭─bollu@cantordust  ~/build/islpy-2016.2.2 ‹2.3.1›
╰─$ python --version
Python 3.6.1
╭─bollu@cantordust  ~/build/islpy-2016.2.2 ‹2.3.1›
╰─$ pip --version
pip 9.0.1 from /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (python 3.6)
```

I'm on Mac OS X El capitan.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

islpy is in [conda-forge](https://conda-forge.github.io/) (including binaries for OSX), you could try installing from there.
